//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.10 at 09:27:11 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://exemplo.com/wsdlservidor/assets", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.exemplo.wsdlservidor.assets;
